"""All http status codes."""
# Errors
PERMISSION_DENIED_ERROR_STATUS_CODE = 403
BAD_REQUEST_ERROR_STATUS_CODE = 400
THIRD_PARTY_API_FAILED_ERROR_STATUS_CODE = 503
COMMON_EXCEPTION_STATUS_CODE = 500
UNAUTHORIZED_ACCESS_STATUS_CODE = 401
PAGE_NOT_FOUND_STATUS_CODE = 404
QUERY_EXCEPTION_STATUS_CODE = 400
CLIENT_CLOSED_REQUEST_STATUS_CODE = 499

# STATUS OK
STATUS_OK = 200
STATUS_CREATED = 201
STATUS_NO_CONTENT = 204
STATUS_ACCEPTED = 202
STATUS_IS_MULTIPLE = 207
REDIRECT_STATUS_CODE = 303
